export type UserSettings = {
    email?: string;
    username?: string;
    profileImageId?: number;
    profileImageName?: string;
    profileImageUrl?: string;
    backgroundImageId?: number;
    backgroundImageName?: string;
    backgroundImageUrl?: string;
    favouriteSportId?: number;
    isFavouriteSportIndividual?: boolean;
    favouriteTeamId?: number;
    favouriteTeamName?: string;
    cityId?: number;
    cityName?: string;
    primaryColor?: string | null;
    secondaryColor?: string | null;
    name?: string | null;
    lastName?: string | null;
    birthDate?: Date | null;
    gender?: string | null;
    nationalityId?: number | null;
    // User Preferences
    showOnlyFavoriteSportContent?: boolean;
    prioritizeNearbyEvents?: boolean;
    showFriendActivitiesInFeed?: boolean;
    pushNewEventsNearby?: boolean;
    pushFriendActivities?: boolean;
    pushChallengeUpdates?: boolean;
    pushTournamentUpdates?: boolean;
    emailEventReminders?: boolean;
    emailTournamentReminders?: boolean;
    emailWeeklyDigest?: boolean;
};
